spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: super
    password: secret
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    default-property-inclusion: NON_NULL
